package Datos;
// Generated 02-nov-2014 22:45:18 by Hibernate Tools 3.6.0


import java.io.Serializable;

/**
 * Afecta generated by hbm2java
 */
public class Afecta  implements java.io.Serializable {


     private int id;
     private Plaga plaga;
     private TipoCultivo tipoCultivo;
     private int peligrosidad;
     private Serializable fechaCreacion;

    public Afecta() {
    }

    public Afecta(int id, Plaga plaga, TipoCultivo tipoCultivo, int peligrosidad, Serializable fechaCreacion) {
       this.id = id;
       this.plaga = plaga;
       this.tipoCultivo = tipoCultivo;
       this.peligrosidad = peligrosidad;
       this.fechaCreacion = fechaCreacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Plaga getPlaga() {
        return this.plaga;
    }
    
    public void setPlaga(Plaga plaga) {
        this.plaga = plaga;
    }
    public TipoCultivo getTipoCultivo() {
        return this.tipoCultivo;
    }
    
    public void setTipoCultivo(TipoCultivo tipoCultivo) {
        this.tipoCultivo = tipoCultivo;
    }
    public int getPeligrosidad() {
        return this.peligrosidad;
    }
    
    public void setPeligrosidad(int peligrosidad) {
        this.peligrosidad = peligrosidad;
    }
    public Serializable getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Serializable fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


