package Datos;
// Generated 02-nov-2014 20:36:45 by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private int idArea;
     private int id;
     private Serializable nombre;
     private Serializable superficie;
     private Serializable fechaCreacion;
     private Serializable fechaActualizacion;
     private int abierto;
     private int activo;
     private Serializable cultivo;
     private Set detallePuntos = new HashSet(0);
     private Set trabajos = new HashSet(0);
     private Set actividads = new HashSet(0);
     private Set aplicacions = new HashSet(0);
     private Set cultivos = new HashSet(0);
     private Set propiedads = new HashSet(0);

    public Area() {
    }

	
    public Area(int idArea, int id, Serializable nombre, Serializable superficie, Serializable fechaCreacion, Serializable fechaActualizacion, int abierto, int activo) {
        this.idArea = idArea;
        this.id = id;
        this.nombre = nombre;
        this.superficie = superficie;
        this.fechaCreacion = fechaCreacion;
        this.fechaActualizacion = fechaActualizacion;
        this.abierto = abierto;
        this.activo = activo;
    }
    public Area(int idArea, int id, Serializable nombre, Serializable superficie, Serializable fechaCreacion, Serializable fechaActualizacion, int abierto, int activo, Serializable cultivo, Set detallePuntos, Set trabajos, Set actividads, Set aplicacions, Set cultivos, Set propiedads) {
       this.idArea = idArea;
       this.id = id;
       this.nombre = nombre;
       this.superficie = superficie;
       this.fechaCreacion = fechaCreacion;
       this.fechaActualizacion = fechaActualizacion;
       this.abierto = abierto;
       this.activo = activo;
       this.cultivo = cultivo;
       this.detallePuntos = detallePuntos;
       this.trabajos = trabajos;
       this.actividads = actividads;
       this.aplicacions = aplicacions;
       this.cultivos = cultivos;
       this.propiedads = propiedads;
    }
   
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Serializable nombre) {
        this.nombre = nombre;
    }
    public Serializable getSuperficie() {
        return this.superficie;
    }
    
    public void setSuperficie(Serializable superficie) {
        this.superficie = superficie;
    }
    public Serializable getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Serializable fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Serializable getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Serializable fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public int getAbierto() {
        return this.abierto;
    }
    
    public void setAbierto(int abierto) {
        this.abierto = abierto;
    }
    public int getActivo() {
        return this.activo;
    }
    
    public void setActivo(int activo) {
        this.activo = activo;
    }
    public Serializable getCultivo() {
        return this.cultivo;
    }
    
    public void setCultivo(Serializable cultivo) {
        this.cultivo = cultivo;
    }
    public Set getDetallePuntos() {
        return this.detallePuntos;
    }
    
    public void setDetallePuntos(Set detallePuntos) {
        this.detallePuntos = detallePuntos;
    }
    public Set getTrabajos() {
        return this.trabajos;
    }
    
    public void setTrabajos(Set trabajos) {
        this.trabajos = trabajos;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }
    public Set getAplicacions() {
        return this.aplicacions;
    }
    
    public void setAplicacions(Set aplicacions) {
        this.aplicacions = aplicacions;
    }
    public Set getCultivos() {
        return this.cultivos;
    }
    
    public void setCultivos(Set cultivos) {
        this.cultivos = cultivos;
    }
    public Set getPropiedads() {
        return this.propiedads;
    }
    
    public void setPropiedads(Set propiedads) {
        this.propiedads = propiedads;
    }




}


