package Datos;
// Generated 02-nov-2014 20:36:45 by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Plaga generated by hbm2java
 */
public class Plaga  implements java.io.Serializable {


     private int id;
     private Serializable nombre;
     private Serializable detallePlaga;
     private Serializable imagen;
     private Serializable fechaCreacion;
     private Serializable fechaActualizacion;
     private Set afectas = new HashSet(0);
     private Set tratas = new HashSet(0);

    public Plaga() {
    }

	
    public Plaga(int id, Serializable nombre, Serializable detallePlaga, Serializable imagen, Serializable fechaCreacion, Serializable fechaActualizacion) {
        this.id = id;
        this.nombre = nombre;
        this.detallePlaga = detallePlaga;
        this.imagen = imagen;
        this.fechaCreacion = fechaCreacion;
        this.fechaActualizacion = fechaActualizacion;
    }
    public Plaga(int id, Serializable nombre, Serializable detallePlaga, Serializable imagen, Serializable fechaCreacion, Serializable fechaActualizacion, Set afectas, Set tratas) {
       this.id = id;
       this.nombre = nombre;
       this.detallePlaga = detallePlaga;
       this.imagen = imagen;
       this.fechaCreacion = fechaCreacion;
       this.fechaActualizacion = fechaActualizacion;
       this.afectas = afectas;
       this.tratas = tratas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Serializable nombre) {
        this.nombre = nombre;
    }
    public Serializable getDetallePlaga() {
        return this.detallePlaga;
    }
    
    public void setDetallePlaga(Serializable detallePlaga) {
        this.detallePlaga = detallePlaga;
    }
    public Serializable getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Serializable imagen) {
        this.imagen = imagen;
    }
    public Serializable getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Serializable fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Serializable getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Serializable fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Set getAfectas() {
        return this.afectas;
    }
    
    public void setAfectas(Set afectas) {
        this.afectas = afectas;
    }
    public Set getTratas() {
        return this.tratas;
    }
    
    public void setTratas(Set tratas) {
        this.tratas = tratas;
    }




}


