package Datos;
// Generated 02-nov-2014 20:36:45 by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int id;
     private Proveedor proveedor;
     private Serializable nombre;
     private Serializable imagen;
     private Serializable anotaciones;
     private Serializable precio;
     private Serializable fechaCreacion;
     private Serializable fechaActualizacion;
     private Set tratas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(int id, Proveedor proveedor, Serializable nombre, Serializable imagen, Serializable anotaciones, Serializable precio, Serializable fechaCreacion, Serializable fechaActualizacion) {
        this.id = id;
        this.proveedor = proveedor;
        this.nombre = nombre;
        this.imagen = imagen;
        this.anotaciones = anotaciones;
        this.precio = precio;
        this.fechaCreacion = fechaCreacion;
        this.fechaActualizacion = fechaActualizacion;
    }
    public Producto(int id, Proveedor proveedor, Serializable nombre, Serializable imagen, Serializable anotaciones, Serializable precio, Serializable fechaCreacion, Serializable fechaActualizacion, Set tratas) {
       this.id = id;
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.imagen = imagen;
       this.anotaciones = anotaciones;
       this.precio = precio;
       this.fechaCreacion = fechaCreacion;
       this.fechaActualizacion = fechaActualizacion;
       this.tratas = tratas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Serializable getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Serializable nombre) {
        this.nombre = nombre;
    }
    public Serializable getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Serializable imagen) {
        this.imagen = imagen;
    }
    public Serializable getAnotaciones() {
        return this.anotaciones;
    }
    
    public void setAnotaciones(Serializable anotaciones) {
        this.anotaciones = anotaciones;
    }
    public Serializable getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Serializable precio) {
        this.precio = precio;
    }
    public Serializable getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Serializable fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Serializable getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Serializable fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Set getTratas() {
        return this.tratas;
    }
    
    public void setTratas(Set tratas) {
        this.tratas = tratas;
    }




}


