package Datos;
// Generated 02-nov-2014 22:45:18 by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Propiedad generated by hbm2java
 */
public class Propiedad  implements java.io.Serializable {


     private int idPropiedad;
     private Propietario propietario;
     private Area area;
     private int id;
     private Serializable nombrePropiedad;
     private Serializable descripcion;
     private int idArea;
     private Serializable fechaCreacion;
     private Serializable fechaActualizacion;
     private Set cultivos = new HashSet(0);

    public Propiedad() {
    }

	
    public Propiedad(int idPropiedad, Propietario propietario, Area area, int id, Serializable nombrePropiedad, Serializable descripcion, int idArea, Serializable fechaCreacion, Serializable fechaActualizacion) {
        this.idPropiedad = idPropiedad;
        this.propietario = propietario;
        this.area = area;
        this.id = id;
        this.nombrePropiedad = nombrePropiedad;
        this.descripcion = descripcion;
        this.idArea = idArea;
        this.fechaCreacion = fechaCreacion;
        this.fechaActualizacion = fechaActualizacion;
    }
    public Propiedad(int idPropiedad, Propietario propietario, Area area, int id, Serializable nombrePropiedad, Serializable descripcion, int idArea, Serializable fechaCreacion, Serializable fechaActualizacion, Set cultivos) {
       this.idPropiedad = idPropiedad;
       this.propietario = propietario;
       this.area = area;
       this.id = id;
       this.nombrePropiedad = nombrePropiedad;
       this.descripcion = descripcion;
       this.idArea = idArea;
       this.fechaCreacion = fechaCreacion;
       this.fechaActualizacion = fechaActualizacion;
       this.cultivos = cultivos;
    }
   
    public int getIdPropiedad() {
        return this.idPropiedad;
    }
    
    public void setIdPropiedad(int idPropiedad) {
        this.idPropiedad = idPropiedad;
    }
    public Propietario getPropietario() {
        return this.propietario;
    }
    
    public void setPropietario(Propietario propietario) {
        this.propietario = propietario;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getNombrePropiedad() {
        return this.nombrePropiedad;
    }
    
    public void setNombrePropiedad(Serializable nombrePropiedad) {
        this.nombrePropiedad = nombrePropiedad;
    }
    public Serializable getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(Serializable descripcion) {
        this.descripcion = descripcion;
    }
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }
    public Serializable getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Serializable fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Serializable getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Serializable fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Set getCultivos() {
        return this.cultivos;
    }
    
    public void setCultivos(Set cultivos) {
        this.cultivos = cultivos;
    }




}


