package Datos;
// Generated 02-nov-2014 20:36:45 by Hibernate Tools 3.6.0


import java.io.Serializable;

/**
 * Trabajo generated by hbm2java
 */
public class Trabajo  implements java.io.Serializable {


     private int idTrabajo;
     private Area area;
     private int id;
     private Serializable descripcion;
     private int cantidadPersonas;
     private int costoTotal;
     private int idArea;
     private Serializable fechaCreacion;
     private Serializable fechaActualizacion;

    public Trabajo() {
    }

    public Trabajo(int idTrabajo, Area area, int id, Serializable descripcion, int cantidadPersonas, int costoTotal, int idArea, Serializable fechaCreacion, Serializable fechaActualizacion) {
       this.idTrabajo = idTrabajo;
       this.area = area;
       this.id = id;
       this.descripcion = descripcion;
       this.cantidadPersonas = cantidadPersonas;
       this.costoTotal = costoTotal;
       this.idArea = idArea;
       this.fechaCreacion = fechaCreacion;
       this.fechaActualizacion = fechaActualizacion;
    }
   
    public int getIdTrabajo() {
        return this.idTrabajo;
    }
    
    public void setIdTrabajo(int idTrabajo) {
        this.idTrabajo = idTrabajo;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(Serializable descripcion) {
        this.descripcion = descripcion;
    }
    public int getCantidadPersonas() {
        return this.cantidadPersonas;
    }
    
    public void setCantidadPersonas(int cantidadPersonas) {
        this.cantidadPersonas = cantidadPersonas;
    }
    public int getCostoTotal() {
        return this.costoTotal;
    }
    
    public void setCostoTotal(int costoTotal) {
        this.costoTotal = costoTotal;
    }
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }
    public Serializable getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Serializable fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Serializable getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Serializable fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }




}


